/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 111.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 112.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 113.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 211.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 212.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 213.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 311.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 312.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 313.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 121.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 122.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 123.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 221.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 222.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 223.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 321.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 322.in  &
/usr/bin/python3 /Users/oliviasaa/Desktop/queues/scheduler_with_test_cases.py 323.in  &